name: tripledes
description: Triple DES and DES block cipher implementation ported from CryptoJS
version: 2.0.1
homepage: https://github.com/johnpryan/tripledes-dart
author: John Ryan <john.p.ryan4@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  test: ^0.12.0
