name: tripledes
description: Triple DES Algrorithm
version: 1.0.0
homepage: https://github.com/johnpryan/tripledes-dart
author: John Ryan <john.p.ryan4@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^0.12.0
